version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=easypeasy
      - MYSQL_DATABASE=backend
    ports:
      - "3306:3306"

volumes:
  db_data: